<HTML>
<HEAD>
<TITLE>mail</TITLE>
</HEAD>
<BODY>
<?
	//define who is to receive the mail
	//(in this case, root of the localhost)
	$mailTo = "root@" . $SERVER_NAME;
	
	//set the subject
	$mailSubject = "Testing Mail";
	
	//build body of the message
	$mailBody = "This is a test of PHP's mail function. ";
	$mailBody .= "It was generated by PHP version ";
	$mailBody .= phpversion();
	
	//add a from header
	$mailHeaders = "From: php@$SERVER_NAME.com\n";
	
	//send mail
	if(mail($mailTo, $mailSubject, $mailBody, $mailHeaders))
	{
		print("Mail successfull sent to $mailTo.");
	}
	else
	{
		print("Mail could not be sent to $mailTo.");
	}
?>
</BODY>
</HTML>